#!/bin/bash
set -e

: "${EVOTING_USER:?EVOTING_USER not set}"
: "${EVOTING_PASSWORD:?EVOTING_PASSWORD not set}"

psql -v ON_ERROR_STOP=1 \
     --username "$POSTGRES_USER" \
     --dbname "$POSTGRES_DB" <<EOSQL

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_roles WHERE rolname = '${EVOTING_USER}'
    ) THEN
        CREATE ROLE ${EVOTING_USER} LOGIN PASSWORD '${EVOTING_PASSWORD}';
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO ${EVOTING_USER};
GRANT USAGE ON SCHEMA public TO ${EVOTING_USER};
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA public TO ${EVOTING_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${EVOTING_USER};
REVOKE UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM ${EVOTING_USER};

EOSQL